language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid

before-script:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install shellcheck"

env:
  SHELLCHECK_OPTS='-e SC2034 -e SC2181 -e SC2015 -e SC2154'

script:
 - bash -c 'shopt -s globstar; shellcheck SOURCES/anicorn'

matrix:
  fast_finish: true
