language: bash

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

env:
  SHELLCHECK_OPTS='-e SC2034 -e SC2181'

script:
 - bash -c 'shopt -s globstar; shellcheck SOURCES/anicorn'

matrix:
  fast_finish: true
